### ISSUE TITLE
week 2 exercise 14

### ISSUE THREAD

**Issue by lramirez** [jttoivon/x#5]
❯ tmc submit
Submitting: part02-e14_vector_lengths
Failed: unittest.loader._FailedTest.test.test_vector_lengths
        Failed to import test module: test.test_vector_lengths
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/app/test/test_vector_lengths.py", line 7, in <module>
    import scipy.linalg
ModuleNotFoundError: No module named 'scipy'

**Comment by lramirez** [comment]
Tests pass locally, but the server gives this error message.
